language: java
sudo: required

addons:
  apt:
    packages:
      - libnetcdf-dev
      - libgsl0ldbl
      - libudunits2-0

cache:
  directories:
    - $HOME/.m2

before_install:
  - wget http://imos-binary.s3-website-ap-southeast-2.amazonaws.com/jobs/nco/nco-latest.deb
  - sudo dpkg -i nco-latest.deb
