name: geoserver-build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Introduces slugified variables; eg "master" instead of "refs/heads/master"
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run the Maven install phase
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run the Maven test phase
        run: mvn test -B

      - name: Create timestamp for release tag-name
        id: tag_name
        run: echo "tag_name=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Cut a release, for download by Ansible
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Frontend (${{ env.GITHUB_REF_SLUG }} - ${{ env.GITHUB_SHA_SHORT }})
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          files: |
            src/main/target/geoserver-*-imas.war

